AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Include:
    - 'app/admin/*'
    - 'app/api/*'
    - 'app/controllers/*'
    - 'app/helpers/*'
    - 'app/models/*'
    - 'app/services/*'
    - 'app/uploaders/*'
    - 'app/workers/*'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IndentationWidth:
  Enabled: false
